spring.application.name=VeoLMS
spring.datasource.url=jdbc:postgresql://localhost:5432/VeoLMS
spring.datasource.username=postgres
spring.datasource.password=Anand2026

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true